<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Waiting for multiple promises</title>
</head>
<body>
    <h1>Waiting for multiple promises</h1>

    <p>
        The Promise constructor has an all method that, given an array of promises, returns a <br>
        promise that waits for all of the promises in the array to finish. It then succeeds, <br>
        yielding an array of result values. If any of the promises in the array fail, the <br>
        promise returned by all fails too (with the failure value from the failing promise).
    </p>
    <p>
        Try to implement something like this yourself as a regular function called all .
    </p>
    <p>
        Note that after a promise is resolved (has succeeded or failed), it canâ€™t succeed or <br>
        fail again, and further calls to the functions that resolve it are ignored. This can <br>
        simplify the way you handle failure of your promise.
    </p>
    <hr>
    <p>This exercise is logged into the developer tools console using console.log()</p>

    <script>
        function all (promises) {
            return new Promise(function (success, fail) {
                var results = [],
                    pending = promises.length;

                promises.forEach(function (promise, i) {
                    promise.then(function (result) {
                        results[i] = result;
                        pending -= 1;

                        if (pending == 0) {
                            success(results);
                        }
                    }, function (error) {
                        fail(error);
                    });
                });

                if (promises.length == 0) {
                    success(results);
                }
            });
        }

        // Test
        all([]).then(function (array) {
            console.log("This should be []:", array);
        });

        function soon (val) {
            return new Promise(function (success) {
                setTimeout(function () {
                    success(val);
                }, Math.random() * 500);
            });
        }

        all([soon(1), soon(2), soon(3)]).then(function (array) {
            console.log("This should be [1, 2, 3]:", array);
        });

        function fail () {
            return new Promise(function (success, fail) {
                fail(new Error("boom"));
            });
        }

        all([soon(1), fail(), soon(3)]).then(function (array) {
            console.log("We should not get here");
        }, function (error) {
            if (error.message != "boom") {
                console.log("Unexpected failure:", error);
            }
        });
    </script>
</body>
</html>